name: app
description: CODE NAME TIKI BAR

publish_to: 'none'

version: 0.0.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.2 #ok
  rxdart: ^0.21.0
  qr_flutter: ^4.0.0
  google_fonts: ^2.0.0 #ok
  file_picker: ^3.0.0
  url_launcher: ^6.0.2
  qr_code_tools: ^0.0.7
  pointycastle: ^2.0.1 #ok
  path_provider: ^2.0.1
  android_intent: ^2.0.0
  cupertino_icons: ^1.0.2 #ok
  #firebase_messaging: ^9.0.0
  flutter_secure_storage: ^4.1.0 #ok
  barcode_scan: ^3.0.1
  uni_links: ^0.4.0
  http: ^0.13.1 #ok
  shared_preferences: ^2.0.5 #ok
  share: ^2.0.1
  sentry_flutter: ^5.0.0 #ok
  package_info: ^2.0.0
  amplitude_flutter: ^2.0.0 #ok
  firebase_core: ^1.0.3 #ok
  firebase_dynamic_links: ^2.0.0 #ok


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/images/

  fonts:
    - family: Koara
      fonts:
        - asset: res/fonts/Koara-Bold.ttf
          weight: 700
        - asset: res/fonts/Koara-Regular.ttf
        - asset: res/fonts/Koara-Light.ttf
          weight: 300
