name: app
description: It's your data. Take back control.
version: 0.2.7+1
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amplitude_flutter: ^3.8.0
  android_intent: ^2.0.2
  barcode_scan2: ^4.2.0
  carousel_slider: ^4.0.0
  email_validator: ^2.0.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  firebase_core: ^1.10.6
  firebase_dynamic_links: ^3.0.2 # TODO update breaking changes for onLink
  flutter_appauth: ^2.2.0
  flutter_lints: ^1.0.4
  flutter_markdown: ^0.6.9
  flutter_secure_storage: ^5.0.2
  googleapis: ^7.0.0
  http: ^0.13.4
  intl_utils: ^2.6.0
  intl: ^0.17.0
  logging: ^1.0.2
  lottie: ^1.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  pointycastle: ^3.4.0
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  sentry_flutter: ^6.2.2
  share_plus: ^3.0.4
  sizer: ^2.0.15
  sqflite_sqlcipher: ^2.1.0
  url_launcher: ^6.0.17
  uuid: ^3.0.5

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - res/images/
    - res/animation/
    - res/md/
    - res/json/
    - res/sql/
  fonts:
    - family: Koara
      fonts:
        - asset: res/fonts/Koara-Bold.ttf
          weight: 700
        - asset: res/fonts/Koara-Regular.ttf
        - asset: res/fonts/Koara-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: res/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: res/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: res/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
    - family: SegoeUI
      fonts:
        - asset: res/fonts/Segoe-UI.ttf