name: app_stash
description: It's your data. Take back control.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  firebase_core: ^1.0.4
  flutter_bloc: ^7.0.0
  package_info: ^2.0.0
  sentry_flutter: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/image/
  fonts:
    - family: Koara
      fonts:
        - asset: res/font/Koara-Bold.ttf
          weight: 700
        - asset: res/font/Koara-Regular.ttf
        - asset: res/font/Koara-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: res/font/NunitoSans-Black.ttf
          weight: 900
        - asset: res/font/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/font/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/font/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/font/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/font/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/font/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/font/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/font/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/font/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/font/NunitoSans-Light.ttf
          weight: 300
        - asset: res/font/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/font/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/font/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic