name: Release

on: push
  #push:
    #branches:
      #- master

jobs:
  build:
    name: Flutter (.aab & .xarchive)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'

      - name: Install Doppler
        uses: dopplerhq/cli-action@v1

      - name: Donwload Secrets
        run: doppler secrets download --no-file --format env-no-quotes >> $GITHUB_ENV
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}

      - name: Multiline Secret
        run: |
          echo 'IOS_PRIVATE_KEY<<EOF' >> $GITHUB_ENV
          doppler secrets get IOS_PRIVATE_KEY --plain >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}

      - name: Android Keystore
        run: echo ${{ env.ANDROID_SIGNER_B64}} | base64 --decode > android/android_signer.jks

      - name: Android keystore.properties
        run: printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=key\nstoreFile=../android_signer.jks' ${{ env.ANDROID_SIGNER_SECRET }} ${{ env.ANDROID_SIGNER_SECRET }} > android/keystore.properties

      - uses: yukiarrr/ios-build-action@v1.3.3
        with:
          project-path: ios/Runner.xcodeproj
          p12-key-base64: ${{ env.IOS_CERTIFICATES_SECRET }}
          p12-cer-base64: ${{ env.IOS_CERTIFICATES_B64 }}
          mobileprovision-base64: ${{ env.IOS_PROVISION_B64 }}
          code-signing-identity: ${{ env.IOS_SIGN_IDENTITY }}
          team-id: ${{ env.IOS_TEAM_ID }}
          workspace-path: ios/Runner.xcworkspace

      - name: Flutter Dependencies
        run: flutter pub get

      - name: Build App Bundle (Android)
        run: flutter build appbundle --build-number=${{ env.GITHUB_RUN_ID }}${{ env.GITHUB_RUN_NUMBER }}

      - name: Build IPA (IOS)
        run: flutter build ipa --build-number=${{ env.GITHUB_RUN_ID }}${{ env.GITHUB_RUN_NUMBER }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/bundle/release/*.aab,build/ios/archive/*.xcarchive"
          replacesArtifacts: false
          token: ${{ secrets.GH_TOKEN }}
          