name: Release

on: push
  #push:
    #branches:
      #- master

jobs:
  build:
    name: Flutter (.aab & .xarchive)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'

      - name: Install Doppler
        uses: dopplerhq/cli-action@v1

      - name: Donwload Secrets
        run: doppler secrets download --no-file --format env-no-quotes >> $GITHUB_ENV
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}

      - name: Android Keystore
        run: echo ${{ env.ANDROID_SIGNER_B64}} | base64 --decode > android/android_signer.jks

      - name: Android keystore.properties
        run: printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=key\nstoreFile=../android_signer.jks' ${{ env.ANDROID_SIGNER_SECRET }} ${{ env.ANDROID_SIGNER_SECRET }} > android/keystore.properties

      - name: iOS Development Certificate
        run: echo ${{ env.IOS_DEV_CERT_B64 }} | base64 --decode > ios/ci/Development.p12

      - name: iOS Distribution Certificate
        run: echo ${{ env.IOS_DIST_CERT_B64 }} | base64 --decode > ios/ci/Distribution.p12

      - name: iOS Development Profile
        run: echo ${{ env.IOS_DEV_PROFILE_B64 }} | base64 --decode > ios/ci/Development.mobileprovision

      - name: iOS Distribution Profile
        run: echo ${{ env.IOS_DIST_PROFILE_B64 }} | base64 --decode > ios/ci/Distribution.mobileprovision

      - name: iOS Keychain
        run:  sh ios/ci/install-certificates.sh

      - name: iOS Distribution Profile
        run: sh ios/ci/install-provisions.sh

      - name: Flutter Dependencies
        run: flutter pub get

      - name: Build App Bundle (Android)
        run: flutter build appbundle --build-number=$GITHUB_RUN_ID$GITHUB_RUN_NUMBER

      - name: Build IPA (IOS)
        run: flutter build ipa --build-number=${{ env.GITHUB_RUN_ID }}${{ env.GITHUB_RUN_NUMBER }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/bundle/release/*.aab,build/ios/archive/*.xcarchive"
          replacesArtifacts: false
          token: ${{ secrets.GH_TOKEN }}
          