name: Release

on: push
  #push:
    #branches:
      #- master

jobs:
  build:
    name: Flutter (.aab & .xarchive)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - uses: dopplerhq/cli-action@v1
      - run: doppler secrets download --no-file --format env-no-quotes >> $GITHUB_ENV;
      - run: echo ${{ env.ANDROID_SIGNER_B64}} | base64 --decode > android/android_signer.jks
      - run: printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=key\nstoreFile=../android_signer.jks' ${{ env.ANDROID_SIGNER_SECRET }} ${{ env.ANDROID_SIGNER_SECRET }} > android/keystore.properties"
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ env.IOS_CERTIFICATES_B64 }}
          p12-password: ${{ env.IOS_CERTIFICATES_SECRET }}
      - uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.mytiki.app
          issuer-id: ${{ env.IOS_ISSUER_ID }}
          api-key-id: ${{ env.IOS_KEY_ID }}
          api-private-key: ${{ env.IOS_PRIVATE_KEY }}
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build appbundle --build-number=${{ env.GITHUB_RUN_ID }}${{ env.GITHUB_RUN_NUMBER }}
      - run: flutter build ipa --build-number=${{ env.GITHUB_RUN_ID }}${{ env.GITHUB_RUN_NUMBER }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/bundle/release/*.aab,build/ios/archive/*.xcarchive"
          replacesArtifacts: false
          token: ${{ secrets.GH_TOKEN }}
