name: Release

on: push
  #push:
    #branches:
      #- master

jobs:
  build:
    name: Flutter (.aab & .xarchive)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - uses: dopplerhq/cli-action@v1
      - run: doppler run --command="echo \$ANDROID_SIGNER_B64 | base64 --decode > android/android_signer.jks & printf 'storePassword=%s\nkeyPassword=%s\nkeyAlias=key\nstoreFile=../android_signer.jks' \$ANDROID_SIGNER_SECRET \$ANDROID_SIGNER_SECRET > android/keystore.properties"
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_CI }}
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build appbundle
      - run: flutter build ipa
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/bundle/release/*.aab,build/ios/archive/*.xcarchive"
          replacesArtifacts: false
          token: ${{ secrets.GH_TOKEN }}
