name: Release

on: push
  #push:
    #branches:
      #- master

jobs:
  build:
    name: Android (APK)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build appbundle
      - run: flutter build ipa
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/bundle/release/*.aab","build/ios/archive/*.xcarchive"
          replacesArtifacts: false
          token: ${{ secrets.GH_TOKEN }}
